name: 'golang-coverage'
description: 'GitHub Action to show golang code coverage in pull requests'
author: 'Your name or organization here'
inputs:
  threshold: # change this
    required: false
    description: 'input description here'
    default: 0
runs:
  using: 'node16'
  main: 'dist/index.js'
